Feature Selection
jp-um/machine_learning_handbook pull request #45
Opened 2019-01-14 01:13 UTC by bertubezz

2019-01-14 10:37 UTC, jp-um commented on terms/featureselection_ab.tex
> +\citet{guyon2003introduction} states that the objective of FS is three-fold: improving the prediction performance of the predictors, providing faster and more cost-effective predictors, and providing
"state" not "states" there are two authors

2019-01-14 10:39 UTC, jp-um commented on terms/featureselection_ab.tex
> +% For example, considering feature $f1$ as shown in Figure \ref{fig:feature_selection}a, it can be seen that $f1$ is a relevant feature because it can distinguish between the classes. Feature $f2$ (F
Feature id should be a subscript $f_{1}$, for f1, f2 etc.

2019-01-14 10:39 UTC, jp-um commented on terms/featureselection_ab.tex
> +\section{Filter Models}\label{sec:fs_filter}\index{feature selection!filter models}
"Feature Selection" in index should be capitalized accordingly

2019-01-14 10:39 UTC, jp-um commented on terms/featureselection_ab.tex
> +  \item \textit{dependency measure}\index{feature selection!dependency measure}: is also known as correlation measure or similarity measure. It measures the ability to predict the value of one variab
Distance capital D -- consistency.

2019-01-14 10:40 UTC, jp-um commented on terms/featureselection_ab.tex
> +Some learning algorithms have in-built mechanisms to deal with feature selection \citep{guyon2003introduction,sammut2017encyclopedia}. This makes the selection of the features more efficient than the
Good.

2019-01-14 10:42 UTC, jp-um requested changes
- Not bad but you need equations to explain some concepts rather than plough through everything
- Not a single note on automated feature selection??  how it is done.  Important.

2019-01-14 22:15 UTC, bertubezz commented
By automated feature selection are you referring to streaming feature selection?

Thanks.

2019-01-15 15:06 UTC, jp-um commented
Automated feature selection is just that.  Using automated ways how to select the best features to build an ML model.  Example using a Genetic Algorithm to find the best performat set of features.

2019-01-17 00:01 UTC, bertubezz commented
I have updated my section with your suggestion and resolved the issues that you mentioned.

Thanks

2019-01-17 22:52 UTC, bertubezz commented
Furthermore, now I am using \nameref to reference sections instead of '_below_'.

2019-01-18 16:53 UTC, merged

2019-01-18 16:53 UTC, jp-um commented
Merged, thanks.